# Generated by Django 2.0.5 on 2018-08-21 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[PGYO]{4}$', '4 characters P(Purple) G(Green) Y(Yellow) and O(Orange) are allowed.')])),
                ('turns', models.IntegerField(choices=[(12, 'Long'), (10, 'Medium'), (8, 'Short')], default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[PGYO]{4}$', '4 characters P(Purple) G(Green) Y(Yellow) and O(Orange) are allowed.')])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='mastermind.Board')),
            ],
        ),
    ]
